### ISSUE TITLE
Recover coins sent to Wrong Address Type LCC instead of LTC

### ISSUE THREAD

**Issue by SFisherlmp** [trezor/trezor-wallet#573] opened 2019-05-28 07:31 UTC
I am inquiring if Trezor has a Recovery for coins sent to a wrong address type of LCC instead of LTC - similar to:

https://trezor.io/recover-coins/

Thank You, Sharon

**Comment by prusnak** [comment] 2019-05-28 08:01
Duplicate of https://github.com/trezor/trezor-wallet/issues/572

**Closed by prusnak** 2019-05-28 08:01 UTC
